import fs from 'fs';

const rawData = [
  // Free without Certificate
  { name: 'Codedex', description: 'Start your coding journey with 200+ hours of interactive programming exercises paired with real-world projects. Explore for free!', link: 'https://www.codedex.io/courses', logo: 'https://avatars.githubusercontent.com/u/105237839?s=200&v=4', category: 'Free without Certificate', tags: ['DATA SCIENCE', 'WEB DEVELOPMENT', 'Computer Science', 'GAME DEVELOPMENT'] },
  { name: 'Udemy', description: 'Udemy helps you build in-demand skills fast and advance your career in a changing job market.', link: 'https://www.udemy.com', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6MDsfy7ltQdCGSxYcslBASDohg9_HWXyrUg&s', category: 'Free without Certificate', tags: ['Ai', 'Development', 'Business', 'Finance & Accounting', 'IT & Software', '...'] },
  { name: 'Cisco Networking Academy', description: 'Free online courses. In-person learning. Certification-aligned pathways in topics like Cybersecurity, Networking, and Python.', link: 'https://www.netacad.com', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0yMNy_n0CevcNHSdusd12-bf940f6c758zQ&s', category: 'Free without Certificate', tags: ['Cybersecurity', 'Networking', 'AI & Data Science', '...'] },
  { name: 'Hp Life', description: 'Improve Your Business Skills With Free Courses From HP LIFE', link: 'https://www.life-global.org', logo: 'https://www.unesco.org/sites/default/files/styles/paragraph_medium_desktop/public/2024-04/hp-logo.jpg.webp?itok=JA3rX04A', category: 'Free without Certificate', tags: ['Communication', 'Digital Business Skills', 'Entrepreneurship', '...'] },
  { name: 'SimpliLearn', description: 'Courses focused on building strong foundational skills for career growth', link: 'https://www.simplilearn.com/skillup-free-online-courses', logo: 'https://play-lh.googleusercontent.com/uphrWz_e_K_pZrPOmCR34A6grxPtva0kM8bhMSgdycrlxiBC7C_JzGtyJLn1mfrRLrg', category: 'Free without Certificate', tags: ['Generative AI', 'AI & Machine Learning', 'Project Management', 'Cyber Security', '...'] },
  { name: 'MyGreatLearning', description: 'Learn for free with courses designed by experts, and get certificates at affordable prices.', link: 'https://www.mygreatlearning.com/academy', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnyPKRPhpQmbmSKlibHdKHSMeBF9ZP9-z6Fw&s', category: 'Free without Certificate', tags: ['Management', 'ChatGPT & Gen AI', '...'] },
  { name: 'Coursera', description: 'Learn new job skills in online courses from industry leaders like Google, IBM, & Meta. Advance your career with top degrees from Michigan, Penn, Imperial & more.', link: 'https://www.coursera.org', logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Coursera-Logo_600x600.svg/2048px-Coursera-Logo_600x600.svg.png', category: 'Free without Certificate', tags: ['Data Analyst', 'Project Manager', '...'] },
  { name: 'Edx', description: 'Learn anything, at any time, from anywhere, with free online courses from edX. Gain in-demand skills from world-renowned institutions to advance or begin your career.', link: 'https://www.edx.org/courses?q=free+online+courses', logo: 'https://moocable.com/journal/media/posts/8/edx.png', category: 'Free without Certificate', tags: ['Artificial intelligence', 'Computer science', '...'] },
  { name: 'W3Schools', description: 'Well organized and easy to understand Web building tutorials with lots of examples of how to use HTML, CSS, JavaScript, SQL, Python, PHP, Bootstrap, Java, XML and more.', link: 'https://www.w3schools.com', logo: 'https://static.vecteezy.com/system/resources/previews/051/336/398/non_2x/w3schools-transparent-logo-free-png.png', category: 'Free without Certificate', tags: ['HTML and CSS', 'JavaScript', 'Backend', '...'] },
  { name: 'Coddy', description: 'The free, fun, and effective way to learn to code!', link: 'https://coddy.tech/', logo: 'https://storage.googleapis.com/coddy-15505.appspot.com/public/coddy-logo-trans.png', category: 'Free without Certificate', tags: ['python', 'c++', 'sql', '...'] },
  { name: 'CodeCademy', description: 'Grow in your career and unlock new opportunities by learning in-demand skills in AI, data, coding, cybersecurity, and more.', link: 'https://www.codecademy.com', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Codecademy_icon.svg', category: 'Free without Certificate', tags: ['python', 'it', 'cybersecurity', '...'] },
  { name: 'FreeCodeCamp', description: 'Advance your career by learning in-demand skills in Programming, DevOps, Cybersecurity, AI Engineering, and English for Developers.', link: 'https://www.freecodecamp.org', logo: 'https://play-lh.googleusercontent.com/MoaYYQjGtmGLhG9HbjCDKyj44kwHj1HfbCI2Am70elRm35vJ-u4y4X5uEJjP97MAAsU=w240-h480-rw', category: 'Free without Certificate', tags: ['Responsive Web Design', 'JavaScript', '...'] },
  { name: 'Alison', description: 'Free online courses with certificates. Join 15 million graduates and empower your career. Study, learn, certify, upskill with free online learning and training', link: 'https://alison.com', logo: 'https://cdn01.alison-static.net/public/html/site/img/alison-icon-default.png', category: 'Free without Certificate', tags: ['it', 'Health', 'Language', '...'] },
  { name: 'Manara', description: 'Level Up Your Tech Career in AI & Cloud, for Free', link: 'https://manara.tech', logo: 'https://bookface-images.s3.amazonaws.com/small_logos/66c946ddc2dbfb955e186610de2e888e7e5dd204.png', category: 'Free without Certificate', tags: ['AWS', 'Ai', '...'] },
  { name: 'Hubspot', description: 'From quick, practical courses to comprehensive certifications, learn everything you need to know about the most sought-after business skills.', link: 'https://academy.hubspot.com/courses', logo: 'https://res.cloudinary.com/startup-grind/image/upload/c_fill,dpr_2.0,f_auto,g_center,h_1200,q_100,w_1200/v1/gcs/platform-data-hubspotacademy/contentbuilder/Untitled%20design%20%286%29_NfJUYLR.png', category: 'Free without Certificate', tags: ['Marketing', 'Sales', 'services', '...'] },
  { name: 'LinkedIn Learning', description: 'Identify the skills you need to advance your career', link: 'https://www.linkedin.com/learning', logo: 'https://www.bathtownshippubliclibrary.org/site-assets/images/logos/linkedin-in-learning-logo.png/@@images/image.png', category: 'Free without Certificate', tags: ['Business', 'Technology', '...'] },
  { name: 'Meta Blueprint', description: 'Build on your professional skills. Grow your marketing career. Earn a Meta Certification.', link: 'https://www.facebook.com/business/learn/certification', logo: 'https://images.credly.com/images/cc2c9a21-84a0-4f80-bcda-eb9dea7aa35c/blob.png', category: 'Free without Certificate', tags: ['Digital Marketing', 'Media Buying', 'Media Planning', 'Creative Strategy', '...'] },
  { name: 'skillshop', description: 'Free Google Ads, Google Marketing Platform....', link: 'https://skillshop.docebosaas.com/learn/signin', logo: 'https://quasa.io/storage/images/news/4s23QuVn17Vt896BEPtKJ5f5ENJ741IVRk5l6PXY.png', category: 'Free without Certificate', tags: ['google ads', '...'] },
  { name: 'Google Grow', description: 'Free digital skills training Whether you re looking to build your business, develop your career, or learn new AI skills, we can help you get started.', link: 'https://grow.google/intl/uk/#filter', logo: 'https://grow.google/root/static/images/og-image.png', category: 'Free without Certificate', tags: ['Ai', 'Cloud Computing', '...'] },
  { name: 'BlockChain', description: 'Blockchain Training Alliance is a leading US-based blockchain education and professional development platform for businesses and individuals. We currently offer 16 online courses for business professionals, developers and specialty focus areas. Join 150,000 students who ve trusted BTA for their online learning.', link: 'https://blockchaintrainingalliance.com/products/building-on-hedera-course', logo: 'https://media.licdn.com/dms/image/v2/C560BAQGTE6AirdyxPg/company-logo_200_200/company-logo_200_200/0/1650992696956/blockchain_training_alliance_logo?e=2147483647&v=beta&t=lteW928eZughspas6L7if-bxKU_AfGXj4gew1hVlxlw', category: 'Free without Certificate', tags: ['Blockchain', 'Ethereum Developer', '...'] },
  { name: 'Linux Foundation', description: 'The Linux Foundation is a neutral, trusted hub for developers and organizations to code, manage, and scale open technology projects and ecosystems.', link: 'https://training.linuxfoundation.org/resources/?_sft_content_type=free-course', logo: 'https://media.licdn.com/dms/image/v2/D4E0BAQEMmIBVAnCNXA/company-logo_200_200/company-logo_200_200/0/1725732561727/the_linux_foundation_training__certification_logo?e=2147483647&v=beta&t=eqF0NKh0TS9SvsRtN-y2bdXZ9tEk8PHvJEOILRse1OA', category: 'Free without Certificate', tags: ['Linux'] },
  { name: 'Class Central', description: 'Class Central aggregates courses from many providers to help you find the best courses on almost any subject, wherever they exist.', link: 'https://www.classcentral.com', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoxQyU6_EWZQ8snX-SHIZkwI0_8xwf1eGKPg&s', category: 'Free without Certificate', tags: ['Anythings'] },
  { name: 'Digitaldefynd', description: '4 Million+ Learners | 96000+ Programs | 120+ Top University Partners.', link: 'https://digitaldefynd.com/free-courses', logo: 'https://i.pinimg.com/280x280_RS/11/35/7c/11357c9a055556df8d34d8cce52bb4e3.jpg', category: 'Free without Certificate', tags: ['Anythings'] },
  // Free with Certificate
  { name: 'satr', description: 'منصة سطر التعليمية توفر دورات تدريبية ومسارات تعليمية في البرمجة، تطوير التطبيقات، الأمن السيبراني، الذكاء الاصطناعي، وعلوم البيانات بإشراف الاتحاد السعودي ...', link: 'https://satr.tuwaiq.edu.sa/all-paths', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKbHtyuNjjly8xeyu8CrFsyXG6fIq5ltYU9llGiYcIAtWe_1kQVEyl8M1hDAsE1FpIT0M&usqp=CAU', category: 'Free with Certificate', tags: ['مسار البرمجة', 'مسار الأمن السيبراني', 'قواعد البيانات', '...'] },
  { name: 'One Million Prompters', description: 'One Million Prompters is an ambitious initiative aimed at equipping one million individuals with the skills to use AI tools as well as AI and Prompt Literacy skills over the next three years.', link: 'https://dub.ai/en/omp/#modules', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQntlVd44N_LClpR7VbmFhvuN1O5KojGP3aWA&s', category: 'Free with Certificate', tags: ['Unleashing the Power of AI', 'Commanding Conversations with AI Chatbots', '...'] },
  { name: 'Coursat', description: 'كورسات هي منصة عربية توفر كورسات مجانية عالية الجودة في مختلف المجالات والتخصصات تسعى إلى رفع مستوى التعليم الإلكتروني في الوطن العربي كما توفر فرصة لأصحاب ...', link: 'https://www.coursat.org/index.php', logo: 'https://mentoraraby.com/wp-content/uploads/2021/03/%D9%83%D9%88%D8%B1%D8%B3%D8%A7%D8%AA.jpg', category: 'Free with Certificate', tags: ['البرمجة', 'التصميم', '...'] },
  { name: 'Edraak', description: 'إدراك هي منصة إلكترونية عربية للمساقات الجماعية مفتوحة المصادر (MOOCs). تم تأسيس إدراك بمبادرة من مؤسسة الملكة رانيا للتعليم والتنمية والتي تحرص على بذل ...', link: 'https://www.edraak.org/explore', logo: 'https://media.licdn.com/dms/image/v2/C4D0BAQF3Rt0FdUD0xw/company-logo_200_200/company-logo_200_200/0/1638265018956/edraak_logo?e=2147483647&v=beta&t=S8fzfJfsJMZ03xZhWMvbD-qjn7Ob8iCUec8RFGYzG10', category: 'Free with Certificate', tags: ['الأعمال والريادة', 'الصحة والتغذية', '...'] },
  { name: 'VCN', description: 'VCN offers courses in digital marketing, copywriting, email marketing, sales, virtual assistant, graphic design, and mobile app development.', link: 'https://virtualcoursesnow.com/courses', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3PtBpfyYZY4kZbbBYTuDaE1sMQgg2B0jxmQ&s', category: 'Free with Certificate', tags: ['Copywriting', 'Email Marketing', 'Digital Marketing', 'Sales', 'Virtual Assistant', '...'] },
  { name: 'Techcampus', description: 'TechCampus ; AWS Certified Cloud Practitioner (CLF-C02) · AI. مجاني ; الاختراق الاخلاقي المعتمد CEH v12 · Cyber. $207.00 ; CyberHack - Practical · General.', link: 'https://techcampus.com/courses', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2LUS3he1Y-BGf2JfyIlVBTWKJwhrWr6KHTA&s', category: 'Free with Certificate', tags: ['network', 'coding', 'cyber', '...'] },
  { name: 'Mahara Tech', description: 'maharatech is an online learning platform, offering high-quality courses authored by Information Technology Institute ITI, All Videos in maharatech Produced ...', link: 'https://maharatech.gov.eg', logo: '', category: 'Free with Certificate', tags: ['Cybersecurity', 'Artificial Intelligence', '...'] },
  // Paid with Certificate
  { name: 'SketchUp Campus', description: 'SketchUp Campus offers in-depth training at your own pace, with courses like Architecture Building, V-Ray for Interiors, and SketchUp Fundamentals.', link: 'https://learn.sketchup.com/collections', logo: 'https://eaglepoint.com/wp-content/uploads/2024/08/sketchup_logo_stacked.jpg', category: 'Paid with Certificate', tags: ['Architecture Building', 'V-Ray', 'LayOut Design', '...'] },
  { name: 'Lmofidclub', description: 'ما الذي ستتعلمه في دورة المفيد · التسويق الرقمي الذكي. الدورة تقدم لك أدوات وتقنيات تسويقية حديثة لزيادة أرباحك وتسهيل جذب العملاء المستهدفين. ستتعلم كيف تستغل ...', link: 'https://lmofidclub.com', logo: 'https://yt3.googleusercontent.com/NedTlTfEFhQjwBEpfL_DJLsgtQiyXe7GLzQgi0Zs5u20NJInguWz-bkngfYEEZVdrLqiKvz37g=s900-c-k-c0x00ffffff-no-rj', category: 'Paid with Certificate', tags: ['Ecommerce'] },
  { name: 'Manhaj', description: 'Manhaj.ma is the ideal platform for students wishing to improve their mathematics skills through an interactive, accessible, and effective approach. Our courses in...', link: 'https://manhaj.ma', logo: 'https://media.licdn.com/dms/image/v2/C4E0BAQG020QC3uicoQ/company-logo_200_200/company-logo_200_200/0/1658016454224?e=2147483647&v=beta&t=bTCTPsFrsifZ4mbMuH1Oz-jALaUONi0rzYP0I0Ww0cQ', category: 'Paid with Certificate', tags: ['Math'] },
  { name: 'Mit', description: 'MIT OpenCourseWare is a web based publication of virtually all MIT course content. OCW is open and available to the world and is a permanent MIT activity.', link: 'https://ocw.mit.edu/search', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOD7wxuOeXxGLNOenUAE8pfdDyA3FGqnPE_dXJCisPtNQewTZDMG0xQKqYF3DpBj6hofc&usqp=CAU', category: 'Paid with Certificate', tags: ['Urban Studies and Planning', 'Mathematics', '...'] },
  { name: 'Harmash', description: 'نوفر لك كل المعرفة و الأدوات التي تحتاجها للوصول إلى هدفك بشكل مجاني من دورات تفاعلية، كتب، مشاريع و نساعدك على تخطي أي مشكلة تواجهها أثناء التعلم', link: 'https://harmash.com', logo: 'https://pbs.twimg.com/profile_images/1553662523999768577/3WYsbIMN_400x400.jpg', category: 'Paid with Certificate', tags: ['frontend', 'backend', '...'] },
  { name: 'Kaggle', description: 'Learn the most important language for data science. Intro to Machine Learning Learn the core ideas in machine learning, and build your first models.', link: 'https://www.kaggle.com/learn', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSETVuceU-uIDgoEeeYxNl0sY4uazMpC_xJxQ&s', category: 'Paid with Certificate', tags: ['Intro to Programming', 'Python', '...'] },
  { name: 'Grafikart', description: 'In this series, I propose we practice together using a practical exercise involving Laravel, Inertia, and React. The idea is to see how to combine them.', link: 'https://grafikart.fr/formations', logo: 'https://pbs.twimg.com/profile_images/1666187459284041731/r-_qeOZM_400x400.jpg', category: 'Paid with Certificate', tags: ['html', 'laravel', '...'] },
  // Open Courseware
  { name: 'Andrew Tate', description: 'Hustler Academys University 1.0 is an online course by ex-kickboxer Andrew Tate, where he lays out the strategies and tips for making money in the real world.', link: 'https://mega.nz/folder/snRDRbKD#NMPf8a3Bms_lNJHZRWqFrg', logo: 'https://yt3.googleusercontent.com/JNMODrvuSV_Ks17kfH7ShVrLwunb9k3bArX8o9s0r5PU3LoyY8rK3xHnIH2uLUzu_o99PRfZ=s900-c-k-c0x00ffffff-no-rj', category: 'Open Courseware', tags: ['...'] },
  { name: 'Freelearninglist', description: 'The best free edu-things on the internet, ranked in order of amazingness, and neatly categorized. Includes YouTube channels, Podcasts, eBooks, Courses, ...', link: 'https://freelearninglist.org', logo: 'https://a.thumbs.redditmedia.com/aP9-U-BgD4Aj8m7VkTlgT4HFzyEt8-FW-aK8e0fiaw8.png', category: 'Open Courseware', tags: ['...'] },
  { name: 'Downloadlynet', description: 'Downloading from dl3 and dl4 servers is restricted by our Data Center; VIP servers are working', link: 'https://downloadlynet.ir', logo: 'https://downloadlynet.ir/wp-content/uploads/2025/11/REACONVERTER-PRO2.png', category: 'Open Courseware', tags: ['...'] },
  { name: 'Discudemy', description: 'Discudemy is free way of learning from beginner to professional in a way that everybody can understand. Find best Udemy Promo Codes and Deals on this page.', link: 'https://www.discudemy.com', logo: 'https://media.licdn.com/dms/image/v2/C4D0BAQGyiyeS0PWpxg/company-logo_200_200/company-logo_200_200/0/1630557872079/discudemy__logo?e=2147483647&v=beta&t=6f-Fz1DZsjDk6jfeXiyKHx8cCl6lAUAPkNflOUHvtY0', category: 'Open Courseware', tags: ['...'] },
  { name: 'Hacksnation', description: 'A community where Everyone can Learn, Discuss, Help, and share knowledge. Cybersecurity, Tutorials, Ethical Hacking, Guides, Software, Useful Methods, Free, ...', link: 'https://hacksnation.com', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyINr3Ud5Ixc35kw__H8d4bYRgIwxwvbcNlKuAxyQdPIMSzw4tMb5aXl5ipIU2jUPJ9Jw&usqp=CAU', category: 'Open Courseware', tags: ['...'] },
  { name: 'OneHack', description: 'OneHack a.k.a 1Hack. A community for late-night curiosity, diving deep into AI and 1Hack to uncover answers that others might overlook.', link: 'https://onehack.us', logo: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeHvwtapTC575TmmjSgisx3G3IaOrIH8HXxQ&s', category: 'Open Courseware', tags: ['...'] },
];

const categoriesMap = {
  'Free with Certificate': { title: 'Free with Certificate', entries: [] },
  'Free without Certificate': { title: 'Free without Certificate', entries: [] },
  'Paid with Certificate': { title: 'Paid with Certificate', entries: [] },
  'Open Courseware': { title: 'Open Courseware', entries: [] }
};

rawData.forEach(item => {
  let pricing = 'Free';
  if (item.category.includes('Paid')) pricing = 'Paid';
  if (item.category === 'Open Courseware') pricing = 'Free';
  
  categoriesMap[item.category].entries.push({
    title: item.name,
    url: item.link,
    description: item.description,
    pricing: pricing,
    iconUrl: item.logo,
    tags: item.tags || []
  });
});

const subcategories = Object.values(categoriesMap);

const learningPlatformsStr = `  'learning-platforms': {
    id: 'learning-platforms',
    title: 'Learning Platforms',
    description: 'Platforms for learning and education.',
    subcategories: ${JSON.stringify(subcategories, null, 6).replace(/\]\n      \}/g, ']\n    }')}
  }
};`;

const dbPath = './src/data/database.ts';
let dbContent = fs.readFileSync(dbPath, 'utf-8');

// Replace the old learning-platforms section
dbContent = dbContent.replace(/  'learning-platforms': \{[\s\S]*?\};\n?$/, learningPlatformsStr + '\n');

fs.writeFileSync(dbPath, dbContent);
console.log('Updated database.ts');
